apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 317886643503.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 317886643503.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 80e919e5
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
